### ISSUE TITLE
Elements Lost Behind Pools

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#879] opened 2019-12-03 16:13 UTC
In this video you can see connector elements getting lost behind a process in a pool. This should not happen.

https://www.dropbox.com/s/hws2lq3gan67yk1/elements-falling-behind.mp4?dl=0

**Comment by velkymx** [comment] 2019-12-03 16:41
This is using the Send Email connector.

BPMN:

[leave_of_absence_process.json.txt](https://github.com/ProcessMaker/modeler/files/3917682/leave_of_absence_process.json.txt)

**Comment by chipit24** [comment] 2019-12-03 21:32
I dug into this a little but could not reproduce any bugs related to pools or overlapping elements as shown in the video. I extracted the BPMN file and uploaded it here: https://www.dropbox.com/s/wa40qfd5rv87qyq/leave_of_absence_process.bpmn?dl=0.

In standalone I'm able to upload and interact with the process just fine; there were no covered elements. I did have issues trying to upload the process in core, but that's unrelated (it complained about unknown connector or 'configuration' attribute not allowed).

**Comment by chipit24** [comment] 2019-12-04 18:26
I installed the connector send email package and was able to successfully import the process, however, I did not encounter any issues with hidden elements. This was tested on macOS Catalina on Chrome 78 using the latest develop branch of processmaker.

Here is a video of what it looks like for me:
https://www.dropbox.com/s/oxzwgx0r5dchzpw/no-overlapping-email-connector.mov?dl=0

@velkymx Echoing what @JCook21 said, we'll need some reproduction steps to make any further progress on this issue.

**Comment by velkymx** [comment] 2019-12-04 18:41
Here's the reproduction of the bug: 

https://www.dropbox.com/s/jc9tbsgtjsd0707/send-email-modeler-bug.mp4?dl=0

**Comment by chipit24** [comment] 2019-12-05 16:00
Adding my update from our Slack conversation here for context:

> The issue is fixed for the ABE connector as well. And it seems to have been fixed by https://github.com/ProcessMaker/package-actions-by-email/pull/25, as when I checkout the commit before I see that the crown doesn’t load, and the connector disappears behind the pool.

It appears the issue is with how connectors interact with the new crown, and connectors will need to be updated as mentioned in the quote above.

**Comment by chipit24** [comment] 2019-12-05 21:58
Removing from the current sprint as there's currently no work in to do for this issue in the modeler.

**Comment by chipit24** [comment] 2020-01-06 19:01
Closing as can't reproduce.

**Closed by chipit24** 2020-01-06 19:01 UTC
Labels: P1, bug
