### ISSUE TITLE
Mini-Map Click Away Warning

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#673] opened 2019-09-23 21:53 UTC
# Bug report issue
## Description
Using the map forces the JS "are you sure you want to leave" message, even if you've not modified anything
## Reproduction steps
Load a process, click on the map to recenter.
## Expected behaviour
The leaving dialog should not show when the map is clicked.

**Comment by JCook21** [comment] 2019-09-24 14:02
Given the description above I cannot reproduce this. Below is a link to a screen recording on Dropbox showing what I tried. If this is still an issue can you add more details in terms of reproduction steps, a video of that you see and information on the browser and OS you're using? I'll assign this to you for now.

https://www.dropbox.com/s/uo5yxqufz4qyo8d/Screen%20Recording%202019-09-24%20at%209.56.48%20AM.mov?dl=0

**Comment by PMQABen** [comment] 2019-09-24 23:09
Occurs in Firefox and MSE, you do not need to enable the mini-map to make the JS message appear.

**Comment by JCook21** [comment] 2019-09-25 13:01
Thanks @PMQABen. In the future could you add information about browsers you've seen issues with when you create a bug report? This will help minimize back and forth on issues.

**Comment by chipit24** [comment] 2019-09-25 14:32
Looking into the issue, it appears to be related to this file in processamker: https://github.com/ProcessMaker/processmaker/blob/aa9b28a0057083a8f8b34e1c8c60132ce332aab3/resources/js/leave-warning.js.

Chrome respects `event.returnValue` but FireFox is causing the prompt to display even when `noUnsavedChanges` is true.

**Comment by JCook21** [comment] 2019-09-25 14:39
@PMQABen @velkymx this is not an issue with the modeler project so I'm going to close this. Could you please reopen this in the process maker project instead? Rob's comment above should give enough information to get started on this.

**Closed** 2019-09-25 14:39 UTC
Labels: blocker, bug
