### ISSUE TITLE
Modeler inspector has weird scrolling

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#963] opened 2019-12-17 16:14 UTC
When using a package, we are seeing some weird scrolling happening. It's as if the inspector isn't h100.

https://www.dropbox.com/s/8pp15tnqfx6u65a/inspector-scrolling.mov?dl=0

**Comment by chipit24** [comment] 2019-12-17 18:24
I'm unable to reproduce this issue. I'm testing on the latest develop branch on processmaker and I see this:
<img width="558" alt="Screen Shot 2019-12-17 at 1 19 35 PM" src="https://user-images.githubusercontent.com/7561061/71023154-24265600-20d0-11ea-8541-2bd15f30bc22.png">

The view-form-renderer page doesn't have 100% height; I can go through modeler and ensure that all the containers in the inspector have 100% height. However, unless I'm able to reproduce this, I won't be able to add a regression test, and I won't be certain that I made a change and didn't break the layout for some other scenario.

@velkymx do you know what element and package this issue is happening with? And what version of processmaker this is on?

**Comment by chipit24** [comment] 2020-02-03 18:48
Closing since we cannot reproduce.

**Closed by chipit24** 2020-02-03 18:48 UTC
Labels: Can't reproduce, bug
