### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1148] opened 2020-03-23 16:44 UTC
When opening modeler, for either a new or existing Process, the following console errors are thrown:
```
[Vue warn]: Error in event handler for "modeler-init": "TypeError: Cannot read property 'container' of undefined"
(found in <Root>)

TypeError: Cannot read property 'container' of undefined
    at getInspectorItems (initialLoad.js?id=52d5ab8785d9d648986e:32467)
    at registerInspectorExtension (initialLoad.js?id=52d5ab8785d9d648986e:32436)
    at Vue.<anonymous> (pdf-connector.js?id=5988c191769c910fe724:1)
    at invokeWithErrorHandling (vendor.js?id=6980491c2e4c33f62a76:106048)
    at Vue.$emit (vendor.js?id=6980491c2e4c33f62a76:108074)
    at VueComponent.created (initialLoad.js?id=52d5ab8785d9d648986e:33918)
    at invokeWithErrorHandling (vendor.js?id=6980491c2e4c33f62a76:106048)
    at callHook (vendor.js?id=6980491c2e4c33f62a76:108405)
    at VueComponent.Vue._init (vendor.js?id=6980491c2e4c33f62a76:109187)
    at new VueComponent (vendor.js?id=6980491c2e4c33f62a76:109332)

Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'private' of undefined"
found in
---> <VueFormRenderer>
       <InspectorPanel>
         <Modeler>
           <ModelerApp> at resources/js/processes/modeler/components/ModelerApp.vue
             <Root>

TypeError: Cannot read property 'private' of undefined
    at VueComponent.mounted (app.js?id=0d0176700808d1ab58ef:206388)
    at invokeWithErrorHandling (vendor.js?id=6980491c2e4c33f62a76:106048)
    at callHook (vendor.js?id=6980491c2e4c33f62a76:108405)
    at Object.insert (vendor.js?id=6980491c2e4c33f62a76:107331)
    at invokeInsertHook (vendor.js?id=6980491c2e4c33f62a76:110526)
    at VueComponent.patch [as __patch__] (vendor.js?id=6980491c2e4c33f62a76:110743)
    at VueComponent.Vue._update (vendor.js?id=6980491c2e4c33f62a76:108134)
    at VueComponent.updateComponent (vendor.js?id=6980491c2e4c33f62a76:108252)
    at Watcher.get (vendor.js?id=6980491c2e4c33f62a76:108663)
    at Watcher.run (vendor.js?id=6980491c2e4c33f62a76:108738)
```
These errors also appear when you add any control to the modeler layout.

**Comment by chipit24** [comment] 2020-03-23 17:28
@velkymx The 1st console error has been fixed in https://github.com/ProcessMaker/connector-pdf-print/pull/11. A new version of that connector will need to be released and installed.

We're not seeing the other console error either; it may be related to the connector fixes we merged. Once a new modeler, connectors, and core are released these should both be resolved.

**Comment by ZLTM** [comment] 2020-03-25 13:58
Can't see any error on 4.0.3

**Comment by chipit24** [comment] 2020-03-30 18:15
Closing as this appears to be fixed and can't reproduce.

**Closed by chipit24** 2020-03-30 18:15 UTC
Labels: bug
