### ISSUE TITLE
Import Line Drawing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#759] opened 2019-10-22 16:34 UTC
![image](https://user-images.githubusercontent.com/535300/67308495-07deb200-f4af-11e9-9f17-10b46fe765d7.png)

**Comment by velkymx** [comment] 2019-10-22 16:35
BPMN file: https://www.dropbox.com/s/m72k4b472k67aqy/SP.08.DSS02.01%20Correspondence%20with%20Customer%20%28en%29.bpmn?dl=0

**Comment by chipit24** [comment] 2019-10-23 18:39
@velkymx The BPMN file you linked to above is different from the one in the screenshot. I think you mean to link to [_SP.08.DSS02 Manage Service Requests and Incidents (Incident Management) (en).bpmn_](https://www.dropbox.com/s/lq1qbuxzrniwy67/SP.08.DSS02%20Manage%20Service%20Requests%20and%20Incidents%20%28Incident%20Management%29%20%28en%29.bpmn?dl=0)?

Based on the screenshot above, I'm assuming the problem is with unneeded loops or additional vertices being rendered for the following sequence flows: 
 * Loop in the connection from the "Customer is being informed" `intermediateThrowEvent` to the "Functional and/or management escalation?" `inclusiveGateway`.
 * Additional vertex (backwards "h" shaped line) in the sequence flow going into the "Converging Gateway (escalation case)" `inclusiveGateway` from the "Close incident" `userTask`.

The end result of which should look something like how it does in Camunda:
<img width="604" alt="Screen Shot 2019-10-23 at 2 36 05 PM" src="https://user-images.githubusercontent.com/7561061/67423547-75b7d600-f5a2-11e9-8e66-d55c0f5c31b0.png">

The issue with sequence flows going up and down when two elements are very close (like in between the "Perform functional escalation (2nd/3rd level)" user task and the two inclusive gateways) is something we discussed a few times in the past and we may not be able to come up with a quick solution to that without planning out the implementation for a custom sequence flow router.

This also seems to be specific to Adonis files, as I tried to reproduce it within our own modeler and it appears to render correctly:
<img width="639" alt="Screen Shot 2019-10-23 at 2 37 57 PM" src="https://user-images.githubusercontent.com/7561061/67423700-b9aadb00-f5a2-11e9-901c-22700219e098.png">

Let me know if there's something I'm not understanding correctly from this issue.

**Comment by chipit24** [comment] 2019-10-23 20:31
I've simplified the process significantly while keeping the original issue; this may make it easier to debug: https://www.dropbox.com/s/avknhi5i9z3txwn/Adonis_process_with_flow_issues.xml?dl=0.

**Comment by chipit24** [comment] 2019-10-24 13:24
> The issue with sequence flows going up and down when two elements are very close (like in between the "Perform functional escalation (2nd/3rd level)" user task and the two inclusive gateways) is something we discussed a few times in the past and we may not be able to come up with a quick solution to that without planning out the implementation for a custom sequence flow router.

Examining the other sequence flows, it seems this is the problem with all of them.

**Comment by chipit24** [comment] 2020-02-03 19:01
The issue with looping flows for close elements has been resolved in https://github.com/ProcessMaker/modeler/pull/1047. There's no other actionable items from this issue; closing.

**Closed by chipit24** 2020-02-03 19:01 UTC
Labels: blocker, bug
