### ISSUE TITLE
MS Edge Console Errors

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#822] opened 2019-11-14 19:50 UTC
# Bug report issue
## Description
Dragging any element onto the grid will produce a console warning in Microsoft Edge

## Reproduction steps
- Open Modeler in the latest Edge version
- Drag any element onto the grid

## Expected behaviour
- Dragging element onto the grid will not produce any console errors

## Actual behaviour
- Dragging element onto the grid produces console error
<img width="603" alt="Screen Shot 2019-11-21 at 2 08 24 PM" src="https://user-images.githubusercontent.com/26545455/69368842-dea97100-0c68-11ea-93ff-3b573c4da53f.png">

## Software used
- Modeler Version 0.17.5
    - Develop Branch _November 21, 2019_
- Edge Version 18
- Windows 10

**Comment by velkymx** [comment] 2019-11-25 16:33
Use the Edge Chromium version

**Comment by chipit24** [comment] 2019-11-25 17:08
The issue is due to Edge not supporting [`flatMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap), see https://caniuse.com/#search=flatMap. A compatibility table is also listed at the bottom of the MDN reference page.


`flatMap` is supported in the latest Insider version of Edge, which I confirmed is working as expected on macOS Mojave and Windows 10. Closing issue.

**Closed by chipit24** 2019-11-25 17:08 UTC
Labels: bug
