### ISSUE TITLE
Adonis Import Reopen

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#756] opened 2019-10-22 14:00 UTC
# Bug report issue
## Description
When you reopen an import with invalid elements, the BPMN does not load. It shows an empty canvas.
## Reproduction steps
Import the BPMN file: 
https://www.dropbox.com/s/lq1qbuxzrniwy67/SP.08.DSS02%20Manage%20Service%20Requests%20and%20Incidents%20%28Incident%20Management%29%20%28en%29.bpmn?dl=0

Save the file and return the processes list.

Reopen the imported process

Canvas is blank.

Video of issue: 

https://www.dropbox.com/s/tvut2bfh2bxyvh2/Screen%20Recording%202019-10-22%20at%208.03.38%20AM.mov?dl=0

**Comment by velkymx** [comment] 2019-10-22 14:02
screenshot: 

https://www.dropbox.com/s/uaq9lx85rygwszh/import2d.png?dl=0

BPMN:

https://www.dropbox.com/s/m72k4b472k67aqy/SP.08.DSS02.01%20Correspondence%20with%20Customer%20%28en%29.bpmn?dl=0

**Comment by chipit24** [comment] 2019-10-22 14:34
@velkymx I tested this (with the process you linked to) on the standalone modeler and also on the latest processmaker develop branch. I had no problems in either case. This is what it looks like:

<img src="https://www.dropbox.com/s/yfy1278p9v5zxvw/Screen%20Shot%202019-10-22%20at%2010.21.42%20AM.png?raw=1">

https://www.dropbox.com/s/yfy1278p9v5zxvw/Screen%20Shot%202019-10-22%20at%2010.21.42%20AM.png?dl=0

Refreshing the page, or going back to the processes list and re-opening the process still produces that same result as in the screenshot above; no console errors or other issues.

I do get console errors on https://staging-pm4qa.processmaker.net, however, the process still loads as expected. Do you know what version of processmaker and modeler are running on there? Or are you able to provide reproduction steps or a video? It seems the issue may have already been fixed on the latest processmaker develop branch.

**Comment by JCook21** [comment] 2019-10-22 15:08
@velkymx same as issue #757, could you use the template and add all of the information requested in that to this issue? Without that information we don't have enough to go on to reliably reproduce this.

**Comment by velkymx** [comment] 2019-10-22 15:10
https://www.dropbox.com/s/tvut2bfh2bxyvh2/Screen%20Recording%202019-10-22%20at%208.03.38%20AM.mov?dl=0

**Comment by chipit24** [comment] 2019-10-22 19:47
@velkymx We followed your updated steps using the BPMN you provided, both locally and on  https://staging-pm4qa.processmaker.net, and were unable to reproduce the issue. In all cases, the process loads, and the canvas is not blank.

**Comment by chipit24** [comment] 2020-02-03 19:06
Tested in latest modeler and it's working fine. Still can't reproduce; closing.

**Closed by chipit24** 2020-02-03 19:06 UTC
Labels: Can't reproduce, blocker, bug
